name: CI

on:
  pull_request:
    branches: [ dev, prd ]

env:
  node_version: "16"

jobs:
#  test:
#    name: Test
#    runs-on: ubuntu-latest
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#
#      - name: setup node
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ env.node_version }}
#
#      - name: Test App
#        run: npm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - name: Install Packages
        run: npm install

      - name: Lint App
        run: npm run lint
