name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  node_version: "18.x"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - token: NPM_TOKEN
            url: https://registry.npmjs.org
#           - token: GITHUB_TOKEN
#             url: https://npm.pkg.github.com
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: ${{ matrix.registry.url }}
          scope: '@byu-oit'

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token] }}

      - run: npm run lint

      - run: npm publish --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token] }}
