name: Publish tfv to npm registry

on:
  push:
    branches: [prd]

env:
  node_version: "16"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org

      - name: Install Packages
        run: npm install

      - name: Lint App
        run: npm run lint

#      - name: Test
#        run: npm test

      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
